### ISSUE TITLE
Doesn't compile on Mac

### ISSUE THREAD

**Issue by BSalem** [10110111/k4oxygen#12]
when configuring on mac, it asks for Qt5X11ExtrasConfig.cmake, while Qt on mac doesn't use X11

**Comment by 10110111** [comment]
Could you post the whole output of CMake? I don't have a Mac to check it myself.

**Comment by 10110111** [comment]
I've pushed a potential fix. Please retest with current master.

**Comment by BSalem** [comment]
Cool.. thanks for the new update, cmake is passing fine now and most of the code compiles as expected until received these two error(s), I bypassed by commenting out the error lines, then the code compiled, but I'm not sure if the ui will behave as expected though:
k4oxygen-master/libs/imported/oxygennetrootinfo.cpp:53:5: error: use of undeclared
      identifier 'XSendEvent'
    XSendEvent(display, root, False, netwm_sendevent_mask, &e);


k4oxygen-master/libs/imported/oxygennetrootinfo.cpp:59:31: error: use of undeclared
      identifier 'XInternAtom'
    return (net_wm_moveresize=XInternAtom(display,"_NET_WM_MOVERESIZE",False));
                              ^

**Comment by 10110111** [comment]
Thanks for reply. The functionality that's expected not to work without X11 is "drag by empty areas" feature.
I've pushed one more compilation fix. Please check that the style now builds out of the box.

**Comment by BSalem** [comment]
Awesome, now it builds without errors...
Thanks for your support
