### ISSUE TITLE
Qt6 X11Extras is removed

### ISSUE THREAD

**Issue by hazel-bunny** [10110111/k4oxygen#14]
https://doc.qt.io/qt-6/extras-changes-qt6.html#changes-to-qt-x11-extras

Could you consider adapting the code as necessary?

**Comment by 10110111** [comment]
Does it fail to build for you, or you just want nicely rounded menus and translucent tooltips back?

**Comment by 10110111** [comment]
I've made an experimental branch [qt6x11](https://github.com/10110111/k4oxygen/tree/qt6x11) that enables X11-based features on Qt6, please check if it works for you.

**Comment by 10110111** [comment]
An improved version of the fix has been pushed to master as 5fe1fb8ce04ae99b81390310f06a687ed48cfb54.
