### ISSUE TITLE
Broken with dark color schemes

### ISSUE THREAD

**Issue by hazel-bunny** [10110111/k4oxygen#18]
K4Oxygen with [Materia Dark](https://github.com/PapirusDevelopmentTeam/materia-kde):
![Screenshot_20241019_162235](https://github.com/user-attachments/assets/df5a54b7-a607-4237-9e53-5eeba762c56b)

Oxygen with Materia Dark:
![Screenshot_20241019_162445](https://github.com/user-attachments/assets/ba7593f6-0848-4330-b520-42ecda2caaba)

Operating System: Fedora Linux 40
KDE Plasma Version: 6.2.1
KDE Frameworks Version: 6.7.0
Qt Version: 6.7.2
Kernel Version: 6.11.4-201.fsync.fc40.x86_64 (64-bit)
Graphics Platform: Wayland

**Comment by 10110111** [comment]
Does this patch help? (Is `kf6-config` the right command in modern KDE?)
```diff
diff --git a/libs/imported/oxygenconfig.cpp b/libs/imported/oxygenconfig.cpp
index 734d73b..e538f5a 100644
--- a/libs/imported/oxygenconfig.cpp
+++ b/libs/imported/oxygenconfig.cpp
@@ -62,6 +62,9 @@ QStringList getConfigPaths()
     if(process.waitForFinished() && process.exitCode()==0)
         return QString::fromUtf8(process.readAllStandardOutput()).trimmed().split(':');
     process.start("kf5-config",args);
+    if(process.waitForFinished() && process.exitCode()==0)
+        return QString::fromUtf8(process.readAllStandardOutput()).trimmed().split(':');
+    process.start("kf6-config",args);
     if(process.waitForFinished() && process.exitCode()==0)
         return QString::fromUtf8(process.readAllStandardOutput()).trimmed().split(':');
 
```

**Comment by 10110111** [comment]
Oh, sorry, that patch shouldn't have worked even if `kf6-config` existed. But anyway, I've now checked that `kf6-config` doesn't exist on Kubuntu 24.10 (and isn't available from repos), so I suppose we have to assume the default location as the fallback.
Please check the following patch.
```diff
diff --git a/libs/imported/oxygenconfig.cpp b/libs/imported/oxygenconfig.cpp
index 98108b1..045ecf8 100644
--- a/libs/imported/oxygenconfig.cpp
+++ b/libs/imported/oxygenconfig.cpp
@@ -68,6 +68,9 @@ QStringList getConfigPaths()
     // Resort to user config dir
     QString dirName=userConfigDir()+"/k4oxygen";
     if(QDir(dirName).exists()) return QStringList(dirName);
+    // If no k4oxygen-specific config file exists, try the default location for KF6
+    dirName = userConfigDir();
+    if(QDir(dirName).exists()) return QStringList(dirName);
     return QStringList();
 }
 
```

**Comment by 10110111** [comment]
> You mean [kf6-kconfig](https://launchpad.net/ubuntu/+source/kf6-kconfig) ? It exists in Ubuntu.

I mean the app that would give me the path to the directory with `kdeglobals` as `kf5-config` and `kde4-config` used to. According to [BLFS](https://lfs.maru-na.net/blfs/view/systemd/kde/frameworks6.html), `kf6-config` existed in KDE Frameworks 6.5.0, but according to [this thread](https://discuss.kde.org/t/replacement-for-kwriteconfig5-in-plasma6/12230) it got deprecated at some point, so we can't rely on it. And the suggested `qtpaths` requires me to install `qtchooser` on Ubuntu, which is less than useful.

**Comment by 10110111** [comment]
Interesting. Is it after the latest commit in `master`? Does it work better before it?
